common: &common
    adapter: mysql2
    host: localhost
    encoding: utf8
    username: root
    pool: 50
    timeout: 5000
    reconnect: true
    options:
      useUnicode: true
      collation: utf8_general_ci
      connectionCollation: utf8_general_ci

development:
  <<: *common
  database: zappistore_devtest_development

production:
  <<: *common
  database: zappistore_devtest_production

test: &test
  <<: *common
  database: zappistore_devtest_test
